vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        avatar_images:
            uri_prefix: '%avatar_images%'
            upload_destination: '%kernel.project_dir%/public%avatar_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
