version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jessy_hair_app
    volumes:
      - .:/var/www/symfony:delegated
      - /var/www/symfony/var
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql://symfony:password@db:3306/hair_star?serverVersion=mariadb-10.5.0"

  db:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      MYSQL_DATABASE: hair_star
      MYSQL_USER: symfony
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: symfony
      PMA_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data: {}
  nginx_logs: {}
