controllers:
  resource: ../../src/Controller/*
  exclude: ../../src/Controller/Admin
  type: attribute
admin_controllers:
  name_prefix: app_admin_
  prefix: '%admin_prefix%'
  resource: ../../src/Controller/Admin/*
  type: attribute
api_controllers:
  name_prefix: api_
  prefix: /api
  resource: ../../src/Controller/Api/
  type: attribute
