# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  admin_prefix: '%env(resolve:ADMIN_PREFIX)%'
  admin_email: '%env(ADMIN_EMAIL)%'
  sender_email: '%env(SENDER_EMAIL)%'
  app.name: '%env(APP_NAME)%'
  stripe_webhook_secret: '%env(STRIPE_WEBHOOK_SECRET)%'
  timezone: 'Europe/Paris'
  realisation_img_dir: '%kernel.project_dir%/public/uploads/images/realisations'
  upload_images_directory: '%kernel.project_dir%/public/uploads/images'
  avatar_images: '/uploads/avatars'

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/'
    exclude:
      exclude: '../src/{DependencyInjection,Entity,Infrastructure/Migrations,Tests,Kernel.php}'

  App\Http\Controller\:
    resource: '../src/Http/Controller'
    tags: [ 'controller.service_arguments' ]

  App\Http\Admin\Controller\:
    resource: '../src/Http/Admin/Controller'
    tags: [ 'controller.service_arguments' ]

  App\Http\Api\Controller\:
    resource: '../src/Http/Api/Controller'
    tags: [ 'controller.service_arguments' ]

  App\Helper\Paginator\PaginatorInterface:
    class: App\Helper\Paginator\KnpPaginator

  App\Helper\MinutesToTimeHelper: ~

  App\Infrastructure\Mailing\MailService:
    arguments:
      $senderEmail: '%sender_email%'

  App\Domain\Prestation\Form\PrestationForm:
    arguments:
      $transformer: '@App\Helper\MinutesToTimeHelper'


  App\Form\Type\SwitchboxType:
    tags:
      - { name: 'form.type' }


  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones

  App\Infrastructure\AppConfigService:
    arguments:
      $appName: '%app.name%'
      $adminEmail: '%admin_email%'

  App\Domain\Payment\Stripe\StripeApi:
    arguments:
      $privateKey: '%env(STRIPE_SECRET_KEY)%'

  App\Domain\Application\EventListener\ExceptionListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception }

# TODO: Si besoin d'utiliser le nom de l'application en BDD dans les templates, décommenter les lignes ci-dessous
#  App\Domain\Application\EventListener\ConfigListener:
#    tags:
#      - { name: 'kernel.event_listener', event: 'kernel.request', method: 'onKernelRequest' }
